### ISSUE TITLE
macos: oplot window doesn't close

### ISSUE THREAD

**Issue by anentropic** [sanette/oplot#3]
When I press `esc` to close the oplot window:

- fps logging stops and it returns to a fresh utop prompt, but the window stays open (and I get 'rainbow wheel' busy mouse pointer if I move it over the window)
- if I look in the task bar there are two items: "XQuartz" and "ocamlrun"
- I can "quit" XQuartz but nothing happens. I have to "force quit" ocamlrun, at this point the oplot window closes (and also utop crashes with _"Fatal error: exception UTop_main.Term(-11)"_)

I've mostly been testing from `utop`, but same behaviour in `ocaml` shell.

We tried a few tweaks already, see here https://github.com/sanette/oplot/issues/2#issuecomment-1328734209 but so far this behaviour persists

**Comment by sanette** [comment]
I tried on a MacBook pro intel 11.6.5, and I don't have this issue. After the window closes, I do get a spinning beachball, but it disappears when I click on the utop window.
The ocamlrun taks stays in the dock, but normally quits when I exit utop.

**Comment by sanette** [comment]
Interesting: on the same machine I have upgraded to Mac OS 13.0.1 and now I have the problem you describe!

**Comment by sanette** [comment]
the window only closes when I exit from utop.

On the positive size: the window is still usable, ie you can send a new plot to it if you wish.

**Comment by sanette** [comment]
So, my guess is that this issue is not oplot related. Whatever you do, I don't think it is normal that a window does not close when calling Sdl.destroy_window...

**Comment by anentropic** [comment]
Yes I am on 13.0.1

(FWIW I am also using iTerm2 rather than the default Terminal app)

But, if I paste the example code into a file like:

```ocaml
open Oplot.Plt

let main () =
  let p = plot sin (-2.) 20. in
  let a = axis 0. 0. in

  display [ Color red; p; Color black; a ]

let _ = main ()
```

and then compile it:
```
ocamlfind ocamlopt -package oplot -thread -linkpkg -o plot.native plot.ml
```

When I run `./plot.native` it works better - I hit esc and the window closes and the program ends, returning cleanly to the prompt.  There is just an "XQuartz" process left running (with icon in the task bar).

I wonder if the problem in utop is related to threads, e.g. I saw this https://discuss.ocaml.org/t/reading-sdl-events-via-tsdl/1052/5?u=anentropic  (same happens if I use ocaml+down instead of utop)

**Comment by sanette** [comment]
yes the issue occurs only when an interactive toplevel is running. Once you quit it, or if you compile your program, everything is fine. You're right, this might be a thread issue. Oplot does not use any thread, but maybe utop does.

**Comment by sanette** [comment]
py-sdl2 also has similar weird issues 
https://github.com/py-sdl/py-sdl2/issues/139
again this related to using SDL2 in an interactive way

**Comment by sanette** [comment]
Ah: I compiled SDL with the option:
```
./configure --enable-video-x11
```
and then run utop with
```
SDL_VIDEODRIVER=x11 utop
```
and then everything runs fine!!

(by default, macos seems to use the "cocoa" video driver)

**Comment by anentropic** [comment]
I assumed because of the XQuartz stuff I was seeing it was already using X11

I haven't tried re-compiling SDL yet (installed via homebrew currently)

If I run `SDL_VIDEODRIVER=x11 utop` I get:
```
Raising up SDL (local pin)...
Hum... Trying again
Raising up SDL (local pin)...
Sdl error SDL ERROR: x11 not available
```

(the `(local pin)` is something I added in the oplot src when we were trying stuff, to be sure I was getting my modified copy)

**Comment by sanette** [comment]
yes same for me, the SDL shipped with homebrew does not have the X11 video driver, I had to download SDL sources and compile them with the flag indicated above in order to make it work

**Comment by sanette** [comment]
Ok I found a (strange) workaround, which does not need to use the "x11" driver.
For me, it seems to solve the problem.
If you want to try, pin the `cocoa_bug_close_window` branch:
```
opam pin https://github.com/sanette/oplot.git#cocoa_bug_close_window
```

**Comment by anentropic** [comment]
Yep, works for me! 👍

**Comment by sanette** [comment]
great. I'm closing this. I guess the bug should be reported upstream to either tsdl, ctypes, or even SDL+cocoa driver, I'm not sure where...

**Comment by sanette** [comment]
But the way, I took advantage of having this mac to fix the scaling with Retina screens. Now the graphics should be much sharper!
```
opam pin git@github.com:sanette/oplot.git
```
