### ISSUE TITLE
ld: library not found for -llablgl

### ISSUE THREAD

**Issue by anentropic** [sanette/oplot#5]
I can run the example code in an ocaml shell now

i.e.
```ocaml
#use "topfind"
#thread
#require "oplot"

open Oplot.Plt

let p = plot sin (-2.) 20.
let a = axis 0. 0.;;

display [ Color red; p; Color black; a ]
```

But if I add `(libraries oplot)` to the dune file of my project, when I `dune build` I get:

```
ld: library not found for -llablgl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "_none_", line 1:
Error: Error while building custom runtime system
```

...this is without yet having any oplot (or lablgl) code of my own, just adding the library.

I can `#require "lablgl"` and open modules from it in an ocaml shell, so it seems installed ok.

Any ideas?

**Comment by sanette** [comment]
I remember when I did the tests with the mac book, I was able to compile with `dune build` the examples in the "bin" directory. And of course it works in linux too. And in fact it must work with all the machines of the ocaml-CI they have when you submit a new package to opam, because the "bin" directory is part of the library, hence it is build when compiling the library... (and they have a MacOS with homebrew, see https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/87c99fb064d7d85d8c519d992960063e583b7302)

What happens if you go to the "bin" directory and `dune exec ./example.exe` ?

**Comment by sanette** [comment]
Maybe another mac issue like this one? 

https://stackoverflow.com/questions/16682156/ld-library-not-found-for-lgsl



> I can `#require "lablgl"` and open modules from it in an ocaml shell, so it seems installed ok.

opening modules is not enough, you need to actually call a function to have the library loaded.

Did you try to reinstall lablgl cleanly?

**Comment by sanette** [comment]
another guess: did you make sure that `dune build` uses the same version of `ocaml` than your toplevel?

**Comment by anentropic** [comment]
Hi, thanks for your help. I guess it's something weird on my system but I'm not sure what to look for.

I did try deleting my switch and reinstalling everything from scratch, but no change.

https://stackoverflow.com/questions/16682156/ld-library-not-found-for-lgsl seems a very similar error. The confusing part there is that `gsl` is a package that installs via homebrew or macports, while `lablgl` is purely from opam. 

I guess I need to add something to my `LD_LIBRARY_PATH` but I had a sniff around in `...opam-repository/packages/lablgl` and didn't see anything that looked likely

**Comment by anentropic** [comment]
and yes if I go into the oplot/bin dir I can `dune exec ./example.exe` and it works fine

**Comment by sanette** [comment]
> and yes if I go into the oplot/bin dir I can `dune exec ./example.exe` and it works fine

that means that "dune build" does work!

**Comment by anentropic** [comment]
yes, I don't understand why it doesn't work in my own project

**Comment by anentropic** [comment]
turns out this was due to having `(modes byte)` in the dune file for my test suite, which I'd added for sake of running the tests with `ocamldebug`

after removing that it builds successfully

**Comment by sanette** [comment]
I'm not sure but this might be a bug in `dune`...
