### ISSUE TITLE
Feasibility of headless mode

### ISSUE THREAD

**Issue by greenbagels** [sanette/oplot#6]
Hello,
First off; thanks for such a useful package! Plotting with this package feels surprisingly expressive and modular.

Is there any possibility of using the module to create plots in a file (lets say, using the png user device) on a headless machine? i.e. via an ssh shell, or Linux's VT100, etc.

I tried on another machine over ssh recently, but receive this error:

```
INFO: Loading Sdl_image, Target = linux
INFO: Loading Sdl_ttf, Target = linux
xdpyinfo:  unable to open display "".
Can't open display
Can't open display
```

I assume it's just passing some errors from SDL along, but I haven't read into the internals; just curious about the practicality of this request!

**Comment by sanette** [comment]
Feel free to reopen
